// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: ServiciosDeCanciones.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_ServiciosDeCanciones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ServiciosDeCanciones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_ServiciosDeCanciones_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type Cancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,3,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	Tamanio       int32                  `protobuf:"varint,4,opt,name=Tamanio,proto3" json:"Tamanio,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
	EsActivada    bool                   `protobuf:"varint,6,opt,name=EsActivada,proto3" json:"EsActivada,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancion) Reset() {
	*x = Cancion{}
	mi := &file_ServiciosDeCanciones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancion) ProtoMessage() {}

func (x *Cancion) ProtoReflect() protoreflect.Message {
	mi := &file_ServiciosDeCanciones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancion.ProtoReflect.Descriptor instead.
func (*Cancion) Descriptor() ([]byte, []int) {
	return file_ServiciosDeCanciones_proto_rawDescGZIP(), []int{1}
}

func (x *Cancion) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Cancion) GetTamanio() int32 {
	if x != nil {
		return x.Tamanio
	}
	return 0
}

func (x *Cancion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Cancion) GetEsActivada() bool {
	if x != nil {
		return x.EsActivada
	}
	return false
}

type RespuestaCancionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	ObjCancion    *Cancion               `protobuf:"bytes,3,opt,name=objCancion,proto3" json:"objCancion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaCancionDTO) Reset() {
	*x = RespuestaCancionDTO{}
	mi := &file_ServiciosDeCanciones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaCancionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaCancionDTO) ProtoMessage() {}

func (x *RespuestaCancionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_ServiciosDeCanciones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaCancionDTO.ProtoReflect.Descriptor instead.
func (*RespuestaCancionDTO) Descriptor() ([]byte, []int) {
	return file_ServiciosDeCanciones_proto_rawDescGZIP(), []int{2}
}

func (x *RespuestaCancionDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaCancionDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaCancionDTO) GetObjCancion() *Cancion {
	if x != nil {
		return x.ObjCancion
	}
	return nil
}

var File_ServiciosDeCanciones_proto protoreflect.FileDescriptor

const file_ServiciosDeCanciones_proto_rawDesc = "" +
	"\n" +
	"\x1aServiciosDeCanciones.proto\x12\tservicios\"%\n" +
	"\vPeticionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\"m\n" +
	"\aCancion\x12\x16\n" +
	"\x06Titulo\x18\x03 \x01(\tR\x06Titulo\x12\x18\n" +
	"\aTamanio\x18\x04 \x01(\x05R\aTamanio\x12\x10\n" +
	"\x03Url\x18\x05 \x01(\tR\x03Url\x12\x1e\n" +
	"\n" +
	"EsActivada\x18\x06 \x01(\bR\n" +
	"EsActivada\"{\n" +
	"\x13RespuestaCancionDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x122\n" +
	"\n" +
	"objCancion\x18\x03 \x01(\v2\x12.servicios.CancionR\n" +
	"objCancion2]\n" +
	"\x12serviciosCanciones\x12G\n" +
	"\rbuscarCancion\x12\x16.servicios.PeticionDTO\x1a\x1e.servicios.RespuestaCancionDTOB\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_ServiciosDeCanciones_proto_rawDescOnce sync.Once
	file_ServiciosDeCanciones_proto_rawDescData []byte
)

func file_ServiciosDeCanciones_proto_rawDescGZIP() []byte {
	file_ServiciosDeCanciones_proto_rawDescOnce.Do(func() {
		file_ServiciosDeCanciones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ServiciosDeCanciones_proto_rawDesc), len(file_ServiciosDeCanciones_proto_rawDesc)))
	})
	return file_ServiciosDeCanciones_proto_rawDescData
}

var file_ServiciosDeCanciones_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ServiciosDeCanciones_proto_goTypes = []any{
	(*PeticionDTO)(nil),         // 0: servicios.PeticionDTO
	(*Cancion)(nil),             // 1: servicios.Cancion
	(*RespuestaCancionDTO)(nil), // 2: servicios.RespuestaCancionDTO
}
var file_ServiciosDeCanciones_proto_depIdxs = []int32{
	1, // 0: servicios.RespuestaCancionDTO.objCancion:type_name -> servicios.Cancion
	0, // 1: servicios.serviciosCanciones.buscarCancion:input_type -> servicios.PeticionDTO
	2, // 2: servicios.serviciosCanciones.buscarCancion:output_type -> servicios.RespuestaCancionDTO
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ServiciosDeCanciones_proto_init() }
func file_ServiciosDeCanciones_proto_init() {
	if File_ServiciosDeCanciones_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ServiciosDeCanciones_proto_rawDesc), len(file_ServiciosDeCanciones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ServiciosDeCanciones_proto_goTypes,
		DependencyIndexes: file_ServiciosDeCanciones_proto_depIdxs,
		MessageInfos:      file_ServiciosDeCanciones_proto_msgTypes,
	}.Build()
	File_ServiciosDeCanciones_proto = out.File
	file_ServiciosDeCanciones_proto_goTypes = nil
	file_ServiciosDeCanciones_proto_depIdxs = nil
}
